{% set name = "gpstime" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/cds/software/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6131d06a1059912559db3ce2a0ea7ffd748181dd9a5e82a7500de99cabcc55df
  patches:
    - entry_point.patch
    # use IERS for leap-seconds.list,
    # see https://git.ligo.org/cds/software/gpstime/-/issues/19
    - iers.patch

build:
  entry_points:
    - gpstime = gpstime.__main__:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
    - setuptools-scm
  run:
    - appdirs
    - coreutils  # [not win]
    - m2-coreutils  # [win]
    - python
    - python-dateutil
    - requests

test:
  requires:
    - pip
  commands:
    # check requirements
    - python -m pip check
    # check entry point
    - gpstime "Jan 1"
    - gpstime 1261872018
    # run test suite
    - python -m unittest discover gpstime.test

about:
  home: https://git.ligo.org/cds/software/gpstime
  dev_url: https://git.ligo.org/cds/software/gpstime
  doc_url: https://cds.docs.ligo.org/software/gpstime/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING-GPL-3
  summary: GPS-aware datetime module
  description: |
    This package provides GPS time conversion utilities, including a
    gpstime subclass of the built-in datetime class with the addition
    of GPS time parsing and conversion methods.

    Leap second data, necessary for GPS time conversion, is expected
    to be provided by the core libc Time Zone Database tzdata.  If for
    some reason the tzdata leapsecond file is not available, a local
    cache of the IETF leap second record will be maintained:

      https://www.ietf.org/timezones/data/leap-seconds.list

    The package can be executed as a command-line GPS conversion utility.
    that uses the gpstime module is also included.  It is a rough
    work-alike to LIGO 'tconvert' utility.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
