{% set name = "gpstime" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/cds/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4b1fd66dfaa15e4ba45cbb34c8303c4e23929b8f33a7e2309d98e0f435cc73f6
  patches:
    - entry_point.patch

build:
  entry_points:
    - gpstime = gpstime.__main__:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-scm
  run:
    - coreutils  # [not win]
    - m2-coreutils  # [win]
    - python
    - python-dateutil
    - requests

test:
  requires:
    - pip
  commands:
    # check requirements
    - python -m pip check
    # check entry point
    - gpstime "Jan 1"
    - gpstime 1261872018
    # run test suite
    - python -m unittest discover gpstime.test

about:
  home: https://git.ligo.org/cds/gpstime
  dev_url: https://git.ligo.org/cds/gpstime
  doc_url: https://cds.docs.ligo.org/gpstime/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING-GPL-3
  summary: GPS-aware datetime module
  description: |
    This package provides GPS time conversion utilities, including a
    gpstime subclass of the built-in datetime class with the addition
    of GPS time parsing and conversion methods.

    Leap second data, necessary for GPS time conversion, is expected
    to be provided by the core libc Time Zone Database tzdata.  If for
    some reason the tzdata leapsecond file is not available, a local
    cache of the IETF leap second record will be maintained:

      https://www.ietf.org/timezones/data/leap-seconds.list

    The package can be executed as a command-line GPS conversion utility.
    that uses the gpstime module is also included.  It is a rough
    work-alike to LIGO 'tconvert' utility.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
