{% set version = "0.4.4" %}

package:
  name: gpstime
  version: {{ version }}

source:
  url: https://git.ligo.org/cds/gpstime/-/archive/{{ version }}/gpstime-{{ version }}.tar.gz
  sha256: 5908069f99884083881aee663a6c9bbb7b87a67b768d61eb299a04dd1c2db091
  patches:
    - entry_point.patch

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - coreutils
    - python
    - python-dateutil
    - requests

test:
  requires:
    - pytest
  imports:
    - gpstime
  commands:
    - gpstime --help
    - python -m unittest discover gpstime.test

about:
  home: https://git.ligo.org/cds/gpstime
  dev_url: https://git.ligo.org/cds/gpstime
  doc_url: https://cds.docs.ligo.org/gpstime/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GPS-aware datetime module
  description: |
    This package provides GPS time conversion utilities, including a
    gpstime subclass of the built-in datetime class with the addition
    of GPS time parsing and conversion methods.

    Leap second data, necessary for GPS time conversion, is expected
    to be provided by the core libc Time Zone Database tzdata.  If for
    some reason the tzdata leapsecond file is not available, a local
    cache of the IETF leap second record will be maintained:

      https://www.ietf.org/timezones/data/leap-seconds.list

    The package can be executed as a command-line GPS conversion utility.
    that uses the gpstime module is also included.  It is a rough
    work-alike to LIGO 'tconvert' utility.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
