{% set name = "gpstime" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://git.ligo.org/cds/software/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f0307060ba285c2b1de3c3194fbca6c121022cf03d5423d79f24ebc07a25f391
  patches:
    - entry_point.patch

build:
  entry_points:
    - gpstime = gpstime.__main__:main
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - setuptools-scm
  run:
    - __unix  # [unix]
    - __win  # [win]
    - appdirs
    - coreutils  # [unix]
    - m2-coreutils  # [win]
    - python >=3.5
    - python-dateutil
    - requests

test:
  requires:
    - pip
  commands:
    # check requirements
    - python -m pip check
    # check entry point
    - gpstime "Jan 1"
    - gpstime 1261872018
    # run test suite
    - python -m unittest discover gpstime.test

about:
  home: https://git.ligo.org/cds/software/gpstime
  dev_url: https://git.ligo.org/cds/software/gpstime
  doc_url: https://cds.docs.ligo.org/software/gpstime/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING-GPL-3
  summary: GPS-aware datetime module
  description: |
    This package provides GPS time conversion utilities, including a
    gpstime subclass of the built-in datetime class with the addition
    of GPS time parsing and conversion methods.

    Leap second data, necessary for GPS time conversion, is expected
    to be provided by the core libc Time Zone Database tzdata.  If for
    some reason the tzdata leapsecond file is not available, a local
    cache of the IERS leap second record will be maintained:

      https://hpiers.obspm.fr/iers/bul/bulc/ntp/leap-seconds.list

    The package can be executed as a command-line GPS conversion
    utility.  In this manor it is a rough work-alike to the LIGO
    "tconvert" utility.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
