{% set name = "gpstime" %}
{% set version = "0.3.3" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: dd26382df3ded8fb203f1ae8c77b3eaee6b5918c4d1bbe4e49721725f11413c8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - gpstime = gpstime.__main__:main
    - ietf-leap-seconds = ietf_leap_seconds:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - coreutils
    - python
    - python-dateutil
    - requests

test:
  imports:
    - gpstime
    - ietf_leap_seconds
  commands:
    - gpstime --help
    - ietf-leap-seconds --help
    - python -m unittest discover gpstime.test

about:
  home: https://git.ligo.org/cds/gpstime
  dev_url: https://git.ligo.org/cds/gpstime
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GPS-aware datetime module
  description: |
    This package provides a gpstime package, including a gpstime subclass
    of the built-in datetime class with the addition of GPS access and
    conversion methods.

    Leap second data is provided by the ietf_leap_seconds module that
    helps automatically maintain a local copy of the IETF leap second
    list:

      https://www.ietf.org/timezones/data/leap-seconds.list

    A command-line GPS data conversion utility that uses the gpstime
    module is also included.  It is a rough work-alike to "tconvert".

extra:
  recipe-maintainers:
    - duncanmmacleod
