# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Jtv252fOqOKODv+y0afNCRGxIuGIPjy3wngWFrMVT2BT/FBWPTc0ti1L53dZnoGrjRgI1r+AyyEaGgzL7fq/5lR+4bjtr7uapPArHG7PN4clgIF7Z5JokaY/hmbDOiacK9xJAZj3Si1uyzP8SIVfbbnAJSpHJEpZ+/g5Da85w7npx6FRgrtpY/zadVXYSXONDE0IkgbUfKKwYfuM/ZWClDAaPl/EBx7RCQHGWd7torTqb3E3Bj95lgnzI0zSZPqX6i7SHVpFYKfjw1f13gxjaVPue2BnmFAbWZKArpabBTGwro77KJ+IrWVvjelhqbz0KpRvu9VoThS+peeSoA4vu7rmEx1LrfwG0I7zkXRqqFhuhaGLyqmIPFaovC+Oo9HFk9kpuib4157FZZQMyhZAgpzBrGqe479Wp+6hfGNsBB60QSNU/WBbxxmQlfIlG/hYoFGrmk9zKGMkZKDzlR9rlw3Nuq1xsEaj/3TDpbgp8ebIek8R7Aa7QanMRjWf2eknvZdNBnkTm4h/HFxnMnUAJeYty5zJFGXq8ruohxEkAZw6FB9j6APeOmJSUMtaIBLIb/gtaZ/zprd1rb6X0PEkhhNVcDAZ6GeI5XxFAZ1h1gv4F/FmkbhlRDVBRpK+uCpRAsAphk6PMmbpoZTamTM6TyedlHjiVC+WVb0hfqp4HOk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
