travis:
  secure:
    BINSTAR_TOKEN: Jtv252fOqOKODv+y0afNCRGxIuGIPjy3wngWFrMVT2BT/FBWPTc0ti1L53dZnoGrjRgI1r+AyyEaGgzL7fq/5lR+4bjtr7uapPArHG7PN4clgIF7Z5JokaY/hmbDOiacK9xJAZj3Si1uyzP8SIVfbbnAJSpHJEpZ+/g5Da85w7npx6FRgrtpY/zadVXYSXONDE0IkgbUfKKwYfuM/ZWClDAaPl/EBx7RCQHGWd7torTqb3E3Bj95lgnzI0zSZPqX6i7SHVpFYKfjw1f13gxjaVPue2BnmFAbWZKArpabBTGwro77KJ+IrWVvjelhqbz0KpRvu9VoThS+peeSoA4vu7rmEx1LrfwG0I7zkXRqqFhuhaGLyqmIPFaovC+Oo9HFk9kpuib4157FZZQMyhZAgpzBrGqe479Wp+6hfGNsBB60QSNU/WBbxxmQlfIlG/hYoFGrmk9zKGMkZKDzlR9rlw3Nuq1xsEaj/3TDpbgp8ebIek8R7Aa7QanMRjWf2eknvZdNBnkTm4h/HFxnMnUAJeYty5zJFGXq8ruohxEkAZw6FB9j6APeOmJSUMtaIBLIb/gtaZ/zprd1rb6X0PEkhhNVcDAZ6GeI5XxFAZ1h1gv4F/FmkbhlRDVBRpK+uCpRAsAphk6PMmbpoZTamTM6TyedlHjiVC+WVb0hfqp4HOk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
